name: Clear Build Caches

on:
  workflow_dispatch:

permissions:
  actions: write

jobs:
  clear-cache:
    runs-on: ubuntu-latest

    steps:
      - name: Delete all caches
        run: |
          gh cache delete --all \
            --succeed-on-no-caches \
            --repo "${GITHUB_REPOSITORY}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
